apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ollama.name }}-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.ollama.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.ollama.service.port }}
      targetPort: {{ .Values.ollama.service.targetPort }}
  type: {{ .Values.ollama.service.type }} 