apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.ollama.name }}-pvc
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ollama.storage.size }} 